# Generated by Django 5.1.7 on 2025-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Comentario',
            new_name='comentario',
        ),
    ]
